CREATE OR REPLACE PROCEDURE DIASEMANA(
NUMERO IN NUMBER)
IS
    V_NUM NUMBER:=NUMERO;
    V_DIA VARCHAR2(9);
BEGIN
    CASE V_NUM
        WHEN 1 THEN V_DIA:='LUNES';
        WHEN 2 THEN V_DIA:='MARTES';
        WHEN 3 THEN V_DIA:='MIERCOLES';
        WHEN 4 THEN V_DIA:='JUEVES';
        WHEN 5 THEN V_DIA:='VIERNES';
        WHEN 6 THEN V_DIA:='SABADO';
        WHEN 7 THEN V_DIA:='DOMINGO';
        ELSE V_DIA:='NO EXISTE';
    END CASE;
    DBMS_OUTPUT.PUT_LINE('EL DIA DE LA SEMANA ES: '||V_DIA);
END;
/
--LLAMADA AL PROCEDIMIENTO
CALL DIASEMANA(1);