
CREATE OR REPLACE FUNCTION MAYOR(
NUMERO1 IN NUMBER,
NUMERO2 IN NUMBER,
NUMERO3 IN NUMBER)
RETURN NUMBER
IS
V_NUM1 NUMBER:=NUMERO1;
V_NUM2 NUMBER:=NUMERO2;
V_NUM3 NUMBER:=NUMERO3;
V_MAYOR NUMBER;
V_NEGATIVO EXCEPTION;
BEGIN
    IF V_NUM1<0 OR V_NUM2<0 OR V_NUM3<0 THEN
        RAISE V_NEGATIVO;
    END IF;

    IF V_NUM2>V_NUM1 THEN
        IF V_NUM2>V_NUM3 THEN
            V_MAYOR:=V_NUM2;
        ELSE
            V_MAYOR:=V_NUM3;
        END IF;
    ELSIF V_NUM1>V_NUM3 THEN
        V_MAYOR:=V_NUM1;
    ELSE
        V_MAYOR:=V_NUM3;
    END IF;
    RETURN V_MAYOR; 
EXCEPTION
    WHEN V_NEGATIVO THEN
    DBMS_OUTPUT.PUT_LINE('UN NUMERO INTRODUCIDO ES NEGATIVO');
    ; 
END;
/
--LLAMAR FUNCION
SELECT MAYOR (2,5,1) FROM DUAL;