CREATE OR REPLACE FUNCTION AREA(
RADIO IN NUMBER)
RETURN NUMBER
IS
    V_AREA NUMBER;
    V_RADIO NUMBER:=RADIO;
    V_NEGATIVA EXCEPTION;
BEGIN
    IF V_RADIO<0 THEN
    RAISE V_NEGATIVA
    END IF;

    V_AREA:= 3.14159 *(RADIO*RADIO);
    RETURN V_AREA;
EXCEPTION
    WHEN V_NEGATIVA THEN
    DBMS_OUTPUT.PUT_LINE('EL RADIO NO PUEDE SER NEGATIVO');
    ;
END;
/
--LLAMADA FUNCION
SELECT AREA(3) FROM DUAL;