CREATE OR REPLACE PROCEDURE ACTUALIZARFECHA(
    NOMBREDEP IN VARCHAR2) 
IS
    V_NOMBREDEP VARCHAR2(30):=NOMBREDEP;
    V_ESTADO VARCHAR2;
    V_MINFECHA DATOSPERSONALES.FECHA_ALTA%TYPE;

BEGIN

    SELECT MIN(FECHA_ALTA)
    INTO V_MINFECHA
    FROM DEPARTAMENTO D, EMPLEADOS E, DATOSPERSONALES DP
    WHERE D.NOMBRE=V_NOMBREDEP
    AND DP.CLAVE_EMPLEADO=E.ID_EMPLEADO
    AND E.ID_DEPARTAMENTO=D.ID_DEPARTAMENTO;

    UPDATE DATOSPERSONALES
    SET FECHA_ALTA = SYSDATE 
    WHERE FECHA_ALTA=V_MINFECHA;
    
    V_ESTADO:='OK';
    DBMS_OUTPUT.PUT_LINE(V_ESTADO);
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRO EL DATO');

END;
/


-- LLAMA AL RPOCEDIMIENTO
CALL ACTUALIZARFECHA('Almacen');

-- COMPROBAR LOS DATOS CAMBIADOS
SELECT *
FROM datospersonales
ORDER BY fecha_alta DESC;
