
CREATE OR REPLACE FUNCTION DEVUELVEAP(
DNI IN VARCHAR2)
RETURN VARCHAR2
IS
    V_AP1 VARCHAR2;
    V_AP2 VARCHAR2;
    V_DNI VARCHAR2:=DNI;
    V_APELLIDOS VARCHAR(50);
BEGIN
    SELECT AP1
    INTO V_AP1
    FROM CONDUCTOR C
    WHERE C.DNI=V_DNI;
    
    SELECT AP2
    INTO V_AP2
    FROM CONDUCTOR C
    WHERE C.DNI=V_DNI;
    
    V_APELLIDOS:=V_AP1||' '||V_AP2;
    
    RETURN V_APELLIDOS;
exception
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE NECONTRO EL DNI');
END;
/
--LLAMADA FUNCION
SELECT DEVUELVEAP('12345678Z') FROM DUAL;
