SET SERVEROUTPUT ON;
create or replace function division (NUM1 NUMBER, NUM2 NUMBER) 
RETURN NUMBER
IS
    V_NUM1 NUMBER:=NUM1;
    V_NUM2 NUMBER:=NUM2;
    V_RESULTADO NUMBER:=0;
BEGIN
    V_RESULTADO:=V_NUM1/V_NUM2;
RETURN V_RESULTADO;
EXCEPTION
    WHEN ZERO_DIVIDE THEN
        DBMS_OUTPUT.PUT_LINE('EL RESULTADO ES MENOR QUE 0');
END;
/
SELECT DIVISION(10, 7) FROM DUAL;